name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim: [v0.9.5, v0.10.0, stable]
    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}

      - name: Setup test dependencies
        run: make deps/mini.nvim

      - name: Run tests
        run: make test
